// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Concrete;

#nullable disable

namespace Sample.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230621143055_SampleDatabase")]
    partial class SampleDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("APR")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("APR");

                    b.Property<int>("AmortizationPeriod")
                        .HasColumnType("int")
                        .HasColumnName("AmortizationPeriod");

                    b.Property<decimal>("BrokerageFee")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("BrokerageFee");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateDisbursed")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("DateDisbursed");

                    b.Property<decimal?>("DisbursedAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DisbursedAmount");

                    b.Property<int?>("FDGGuaranteeId")
                        .HasColumnType("int")
                        .HasColumnName("FDGGuaranteeId");

                    b.Property<decimal>("FinancedAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("FinancedAmount");

                    b.Property<decimal>("InitialExpenses")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("InitialExpenses");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("LenderId")
                        .HasColumnType("int")
                        .HasColumnName("LenderId");

                    b.Property<int>("LoadStatusId")
                        .HasColumnType("int")
                        .HasColumnName("LoadStatusId");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("OutstandingAmount");

                    b.Property<int>("PreAmortizationPeriod")
                        .HasColumnType("int")
                        .HasColumnName("PreAmortizationPeriod");

                    b.Property<int>("RemainingPreAmortizationPeriod")
                        .HasColumnType("int")
                        .HasColumnName("RemainingPreAmortizationPeriod");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RequestedAmount");

                    b.Property<DateTime>("StatusChangingTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("StatusChangingTime");

                    b.Property<int?>("StatusUpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("StatusUpdateUserId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedById");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
